from __future__ import annotations

import os
from pathlib import Path
import shutil
import subprocess
from typing import Any

LANG_ALIASES = {'af': 'af',
 'afr': 'af',
 'afrikaans': 'af',
 'alb': 'sq',
 'albanian': 'sq',
 'am': 'am',
 'amh': 'am',
 'amharic': 'am',
 'ar': 'ar',
 'ara': 'ar',
 'arabic': 'ar',
 'arm': 'hy',
 'armenian': 'hy',
 'az': 'az',
 'aze': 'az',
 'azerbaijani': 'az',
 'baq': 'eu',
 'basque': 'eu',
 'be': 'be',
 'bel': 'be',
 'belarusian': 'be',
 'ben': 'bn',
 'bengali': 'bn',
 'bg': 'bg',
 'bn': 'bn',
 'bo': 'bo',
 'bod': 'bo',
 'bokmal': 'no',
 'bos': 'bs',
 'bosnian': 'bs',
 'bs': 'bs',
 'bul': 'bg',
 'bulgarian': 'bg',
 'bur': 'my',
 'burmese': 'my',
 'ca': 'ca',
 'cat': 'ca',
 'catalan': 'ca',
 'ceb': 'ceb',
 'cebuano': 'ceb',
 'ces': 'cs',
 'chi': 'zh',
 'chinese': 'zh',
 'croatian': 'hr',
 'cs': 'cs',
 'cy': 'cy',
 'cym': 'cy',
 'cze': 'cs',
 'czech': 'cs',
 'da': 'da',
 'dan': 'da',
 'danish': 'da',
 'de': 'de',
 'deu': 'de',
 'dut': 'nl',
 'dutch': 'nl',
 'el': 'el',
 'ell': 'el',
 'en': 'en',
 'eng': 'en',
 'english': 'en',
 'eo': 'eo',
 'epo': 'eo',
 'es': 'es',
 'esperanto': 'eo',
 'est': 'et',
 'estonian': 'et',
 'et': 'et',
 'eu': 'eu',
 'fa': 'fa',
 'farsi': 'fa',
 'fas': 'fa',
 'fi': 'fi',
 'fij': 'fj',
 'fijian': 'fj',
 'fil': 'tl',
 'filipino': 'tl',
 'fin': 'fi',
 'finnish': 'fi',
 'fj': 'fj',
 'fr': 'fr',
 'fra': 'fr',
 'fre': 'fr',
 'french': 'fr',
 'ga': 'ga',
 'galician': 'gl',
 'geo': 'ka',
 'georgian': 'ka',
 'ger': 'de',
 'german': 'de',
 'gl': 'gl',
 'gle': 'ga',
 'glg': 'gl',
 'gre': 'el',
 'greek': 'el',
 'gu': 'gu',
 'guj': 'gu',
 'gujarati': 'gu',
 'ha': 'ha',
 'haitian': 'ht',
 'haitiancreole': 'ht',
 'hat': 'ht',
 'hau': 'ha',
 'hausa': 'ha',
 'haw': 'haw',
 'hawaiian': 'haw',
 'he': 'he',
 'heb': 'he',
 'hebrew': 'he',
 'hi': 'hi',
 'hin': 'hi',
 'hindi': 'hi',
 'hr': 'hr',
 'hrv': 'hr',
 'ht': 'ht',
 'hu': 'hu',
 'hun': 'hu',
 'hungarian': 'hu',
 'hy': 'hy',
 'hye': 'hy',
 'ibo': 'ig',
 'icelandic': 'is',
 'id': 'id',
 'ig': 'ig',
 'igbo': 'ig',
 'ind': 'id',
 'indonesian': 'id',
 'irish': 'ga',
 'is': 'is',
 'isl': 'is',
 'it': 'it',
 'ita': 'it',
 'italian': 'it',
 'ja': 'ja',
 'japanese': 'ja',
 'jav': 'jv',
 'javanese': 'jv',
 'jpn': 'ja',
 'jv': 'jv',
 'ka': 'ka',
 'kan': 'kn',
 'kannada': 'kn',
 'kat': 'ka',
 'kaz': 'kk',
 'kazakh': 'kk',
 'khm': 'km',
 'khmer': 'km',
 'kk': 'kk',
 'km': 'km',
 'kn': 'kn',
 'ko': 'ko',
 'kor': 'ko',
 'korean': 'ko',
 'ku': 'ku',
 'kur': 'ku',
 'kurdish': 'ku',
 'la': 'la',
 'lao': 'lo',
 'lat': 'la',
 'latin': 'la',
 'latvian': 'lv',
 'lav': 'lv',
 'lit': 'lt',
 'lithuanian': 'lt',
 'lo': 'lo',
 'lt': 'lt',
 'lv': 'lv',
 'macedonian': 'mk',
 'mal': 'ml',
 'malay': 'ms',
 'malayalam': 'ml',
 'maltese': 'mt',
 'maori': 'mi',
 'mar': 'mr',
 'marathi': 'mr',
 'may': 'ms',
 'mi': 'mi',
 'mk': 'mk',
 'mkd': 'mk',
 'ml': 'ml',
 'mlt': 'mt',
 'mn': 'mn',
 'mon': 'mn',
 'mongolian': 'mn',
 'mr': 'mr',
 'mri': 'mi',
 'ms': 'ms',
 'msa': 'ms',
 'mt': 'mt',
 'my': 'my',
 'mya': 'my',
 'nb': 'no',
 'ne': 'ne',
 'nep': 'ne',
 'nepali': 'ne',
 'nl': 'nl',
 'nld': 'nl',
 'no': 'no',
 'nob': 'no',
 'nor': 'no',
 'norwegian': 'no',
 'norwegianbokmal': 'no',
 'pa': 'pa',
 'pan': 'pa',
 'pashto': 'ps',
 'per': 'fa',
 'persian': 'fa',
 'pl': 'pl',
 'pol': 'pl',
 'polish': 'pl',
 'por': 'pt',
 'portuguese': 'pt',
 'ps': 'ps',
 'pt': 'pt',
 'punjabi': 'pa',
 'pus': 'ps',
 'ro': 'ro',
 'romanian': 'ro',
 'ron': 'ro',
 'ru': 'ru',
 'rum': 'ro',
 'rus': 'ru',
 'russian': 'ru',
 'samoan': 'sm',
 'serbian': 'sr',
 'si': 'si',
 'sin': 'si',
 'sinhala': 'si',
 'sk': 'sk',
 'sl': 'sl',
 'slk': 'sk',
 'slo': 'sk',
 'slovak': 'sk',
 'slovenian': 'sl',
 'slv': 'sl',
 'sm': 'sm',
 'smo': 'sm',
 'so': 'so',
 'som': 'so',
 'somali': 'so',
 'spa': 'es',
 'spanish': 'es',
 'sq': 'sq',
 'sqi': 'sq',
 'sr': 'sr',
 'srp': 'sr',
 'su': 'su',
 'sun': 'su',
 'sundanese': 'su',
 'sv': 'sv',
 'sw': 'sw',
 'swa': 'sw',
 'swahili': 'sw',
 'swe': 'sv',
 'swedish': 'sv',
 'ta': 'ta',
 'tagalog': 'tl',
 'tam': 'ta',
 'tamil': 'ta',
 'te': 'te',
 'tel': 'te',
 'telugu': 'te',
 'tgl': 'tl',
 'th': 'th',
 'tha': 'th',
 'thai': 'th',
 'tib': 'bo',
 'tibetan': 'bo',
 'tl': 'tl',
 'tr': 'tr',
 'tur': 'tr',
 'turkish': 'tr',
 'uk': 'uk',
 'ukr': 'uk',
 'ukrainian': 'uk',
 'ur': 'ur',
 'urd': 'ur',
 'urdu': 'ur',
 'uz': 'uz',
 'uzb': 'uz',
 'uzbek': 'uz',
 'vi': 'vi',
 'vie': 'vi',
 'vietnamese': 'vi',
 'wel': 'cy',
 'welsh': 'cy',
 'xh': 'xh',
 'xho': 'xh',
 'xhosa': 'xh',
 'yo': 'yo',
 'yor': 'yo',
 'yoruba': 'yo',
 'zh': 'zh',
 'zho': 'zh',
 'zu': 'zu',
 'zul': 'zu',
 'zulu': 'zu'}

class UserVisibleError(RuntimeError):
    """Expected runtime problem that is safe to show in the UI."""

class OperationCancelled(UserVisibleError):
    """Raised when a cancellable operation is stopped by the user."""


def app_config_dir() -> Path:
    if os.name == "nt":
        base = Path(os.environ.get("APPDATA", Path.home() / "AppData" / "Roaming"))
        return base / "g-file" / "subtitle-ai"
    return Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "g-file" / "subtitle-ai"


_UI_TEXT = {
    "error_asr_audio_missing": "Ses/video kaynağı bulunamadı: {path}",
    "error_asr_dependency_missing": "Whisper bağımlılıkları bulunamadı: {error}",
    "error_asr_failed": "Whisper işlemi başarısız: {error}",
    "error_asr_language_unknown": "Kaynak dil bilinmiyor.",
    "error_asr_language_unsupported": "Desteklenmeyen kaynak dil: {language}",
    "error_asr_no_speech": "Konuşma algılanamadı.",
    "error_translation_dependency_missing": "AI çeviri bağımlılıkları bulunamadı: {error}",
    "error_translation_failed": "AI çeviri başarısız: {error}",
    "error_translation_model_invalid": "AI çeviri modeli geçersiz: {path}",
    "error_translation_no_output": "AI çeviri çıktı üretmedi.",
    "error_translation_same_language": "Kaynak ve hedef dil aynı: {language}",
    "error_translation_target_unsupported": "Desteklenmeyen hedef dil: {language}",
    "error_ffmpeg_missing": "FFmpeg bulunamadı. ffmpeg ve ffprobe paketlerini yükleyin.",
}


def ui_text(key: str, **values: Any) -> str:
    template = _UI_TEXT.get(key, key)
    try:
        return template.format(**values) if values else template
    except Exception:
        return template


def ffmpeg_path() -> str:
    override = os.environ.get("GFILE_FFMPEG_PATH", "").strip()
    if override and Path(override).is_file():
        return override
    found = shutil.which("ffmpeg")
    if not found:
        raise UserVisibleError(ui_text("error_ffmpeg_missing"))
    return found


def ffprobe_path(auto_install: bool = False) -> str | None:
    del auto_install
    override = os.environ.get("GFILE_FFPROBE_PATH", "").strip()
    if override and Path(override).is_file():
        return override
    return shutil.which("ffprobe")


def third_party_subprocess_executable(args: list[str]) -> str | None:
    del args
    return None


def third_party_subprocess_env() -> dict[str, str]:
    env = os.environ.copy()
    # Child ffmpeg processes do not need the Python package search path.
    env.pop("PYTHONHOME", None)
    return env


def subprocess_common_kwargs() -> dict[str, Any]:
    kwargs: dict[str, Any] = {"text": True, "encoding": "utf-8", "errors": "replace"}
    if os.name == "nt":
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        startupinfo.wShowWindow = subprocess.SW_HIDE
        kwargs.update({"creationflags": getattr(subprocess, "CREATE_NO_WINDOW", 0), "startupinfo": startupinfo})
    return kwargs
