cmake_minimum_required(VERSION 3.21)
project(GFileSystemIconTests LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_AUTOMOC ON)
find_package(Qt6 REQUIRED COMPONENTS Quick Concurrent Test)
find_package(KF6IconThemes REQUIRED)
find_package(KF6Archive REQUIRED)
add_executable(system-icon-tests tst_systemicons.cpp ../../src/systemiconprovider.cpp)
target_include_directories(system-icon-tests PRIVATE ../../src)
target_link_libraries(system-icon-tests PRIVATE Qt6::Quick Qt6::Concurrent Qt6::Test KF6::IconThemes KF6::Archive)
